# Generated by Django 3.0.2 on 2020-04-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='truck_id',
            new_name='truck_num',
        ),
    ]
