# Generated by Django 3.0.2 on 2020-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonWeb', '0002_auto_20200422_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='truck_id',
            field=models.IntegerField(null=True),
        ),
    ]
