# Generated by Django 3.0.2 on 2020-04-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonWeb', '0002_auto_20200422_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='x_location',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='y_location',
            field=models.IntegerField(null=True),
        ),
    ]
